import json
from pathlib import Path

import openpyxl


ROOT = Path(__file__).resolve().parent
WORKSPACE = ROOT.parent
SOURCE_CANDIDATES = [
    WORKSPACE / "scratch" / "screener_low_carbon_transport.xlsx",
    WORKSPACE / "Screener- Final - Low Carbon Transport_with highlights.xlsx",
    WORKSPACE / "Screener-Low-Carbon-AS-Copy.xlsx",
]
OUT_TS = ROOT / "src" / "app" / "data" / "lowCarbonScreenerData.ts"

AXIS_COLUMNS = [
    ("Need", "Need Axis", 16),
    ("Readiness", "Readiness Axis", 17),
    ("Financeability", "Financeability Axis", 18),
]
STRONG_AXIS_THRESHOLD = 0.70

ECONOMY_ALIASES = {
    "Turkey": "Türkiye",
    "Turkiye": "Türkiye",
    "Taipei, China": "Taipei,China",
}


def clean(value):
    return str(value or "").strip()


def num(value):
    if isinstance(value, (int, float)):
        return float(value)
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def find_source():
    for source in SOURCE_CANDIDATES:
        if source.exists():
            return source
    raise FileNotFoundError(
        "Missing source workbook. Checked: "
        + ", ".join(str(source) for source in SOURCE_CANDIDATES)
    )


def classify_profile(dimensions):
    strong_axes = [item["dimension"] for item in dimensions if item["score"] >= STRONG_AXIS_THRESHOLD]
    if len(strong_axes) >= 3:
        return {
            "profileLabel": "Strong pull across all three axes",
            "profileColor": "#E64B2A",
            "profileTone": "red",
            "strongAxes": strong_axes,
        }
    if len(strong_axes) == 2:
        return {
            "profileLabel": "Stronger pull across two axes",
            "profileColor": "#F5C400",
            "profileTone": "yellow",
            "strongAxes": strong_axes,
        }
    if len(strong_axes) == 1:
        return {
            "profileLabel": f"Focused pull on {strong_axes[0].lower()}",
            "profileColor": "#9EBB1B",
            "profileTone": "green",
            "strongAxes": strong_axes,
        }
    return {
        "profileLabel": "Overall low to moderate focus",
        "profileColor": "#4E9BC3",
        "profileTone": "blue",
        "strongAxes": strong_axes,
    }


def main():
    source = find_source()
    wb = openpyxl.load_workbook(source, read_only=True, data_only=True)
    scoring = wb["Scoring"]

    economies = []
    for row in range(51, scoring.max_row + 1):
        economy = clean(scoring.cell(row, 5).value)
        axis_values = [num(scoring.cell(row, col).value) for _, _, col in AXIS_COLUMNS]
        if not economy or not any(value > 0 for value in axis_values):
            continue
        economy = ECONOMY_ALIASES.get(economy, economy)

        dimensions = []
        for dimension, short_label, col in AXIS_COLUMNS:
            value = round(num(scoring.cell(row, col).value), 4)
            dimensions.append(
                {
                    "dimension": dimension,
                    "shortLabel": short_label,
                    "score": value,
                    "maxScore": 1,
                    "normalized": round(value * 100, 2),
                }
            )

        average_score = round(sum(item["score"] for item in dimensions) / len(dimensions), 4)
        profile = classify_profile(dimensions)
        economies.append(
            {
                "economy": economy,
                "score": average_score,
                "dimensions": dimensions,
                **profile,
            }
        )

    economies.sort(key=lambda item: (-item["score"], item["economy"]))
    for index, economy in enumerate(economies, start=1):
        economy["rank"] = index

    by_economy = {economy["economy"]: economy for economy in economies}
    dimension_meta = [
        {
            "dimension": dimension,
            "shortLabel": short_label,
            "maxScore": 1,
        }
        for dimension, short_label, _ in AXIS_COLUMNS
    ]

    OUT_TS.write_text(
        "// Auto-generated by build_low_carbon_screener_data.py\n"
        "// Do not edit manually.\n\n"
        "export type LowCarbonScreenerDimension = { dimension: string; shortLabel: string; score: number; maxScore: number; normalized: number };\n\n"
        "export type LowCarbonScreenerEconomy = { economy: string; score: number; rank: number; dimensions: LowCarbonScreenerDimension[]; profileLabel: string; profileColor: string; profileTone: string; strongAxes: string[] };\n\n"
        f"export const LOW_CARBON_SCREENER_DIMENSIONS = {json.dumps(dimension_meta, ensure_ascii=False, indent=2)} as const;\n\n"
        f"export const LOW_CARBON_SCREENER_RANKING: LowCarbonScreenerEconomy[] = {json.dumps(economies, ensure_ascii=False, indent=2)};\n\n"
        f"export const LOW_CARBON_SCREENER_BY_ECONOMY: Record<string, LowCarbonScreenerEconomy> = {json.dumps(by_economy, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"Read {source}")
    print(f"Wrote {OUT_TS}")


if __name__ == "__main__":
    main()
