import json
from pathlib import Path

import openpyxl


ROOT = Path(__file__).resolve().parent
WORKSPACE = ROOT.parent
SOURCE = WORKSPACE / "Screener-Low-Carbon-AS-Copy.xlsx"
OUT_TS = ROOT / "src" / "app" / "data" / "lowCarbonScreenerData.ts"

DIMENSION_SHORT_LABELS = {
    "Infrastructure": "Infrastructure",
    "Transport Activity": "Activity",
    "Fuel Transition": "Fuel Transition",
    "Transport Carbon Emissions": "Emissions",
    "Low Carbon Transport Policies": "Policies",
    "Co-Benefits": "Co-Benefits",
    "Economic and Financial": "Economic",
    "Institutional": "Institutional",
    "International Support": "Support",
}

ECONOMY_ALIASES = {
    "Turkey": "Türkiye",
    "Turkiye": "Türkiye",
    "Taipei, China": "Taipei,China",
}


def clean(value):
    return str(value or "").strip()


def num(value):
    if isinstance(value, (int, float)):
        return float(value)
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def get_dimension_weights(wb):
    ws = wb["Weight"]
    weights = {}
    for row in range(1, ws.max_row + 1):
        dimension = clean(ws.cell(row, 14).value)
        value = ws.cell(row, 15).value
        if dimension and isinstance(value, (int, float)):
            weights[dimension] = float(value)
    return weights


def main():
    if not SOURCE.exists():
        raise FileNotFoundError(f"Missing source workbook: {SOURCE}")

    wb = openpyxl.load_workbook(SOURCE, read_only=False, data_only=True)
    scoring = wb["Scoring"]
    weights = get_dimension_weights(wb)

    dimension_by_col = {}
    current_dimension = ""
    for col in range(3, scoring.max_column + 1):
        dimension = clean(scoring.cell(2, col).value)
        if dimension:
            current_dimension = dimension
        if current_dimension:
            dimension_by_col[col] = current_dimension

    economies = []
    for row in range(5, scoring.max_row + 1):
        economy = clean(scoring.cell(row, 2).value)
        if not economy:
            continue
        economy = ECONOMY_ALIASES.get(economy, economy)
        score = round(num(scoring.cell(row, 1).value), 4)
        dimension_scores = {dimension: 0.0 for dimension in weights}
        for col, dimension in dimension_by_col.items():
            if dimension in dimension_scores:
                dimension_scores[dimension] += num(scoring.cell(row, col).value)

        dimensions = []
        for dimension, max_score in weights.items():
            value = round(dimension_scores.get(dimension, 0.0), 4)
            dimensions.append(
                {
                    "dimension": dimension,
                    "shortLabel": DIMENSION_SHORT_LABELS.get(dimension, dimension),
                    "score": value,
                    "maxScore": round(max_score, 4),
                    "normalized": round((value / max_score) * 100, 2) if max_score else 0,
                }
            )

        economies.append(
            {
                "economy": economy,
                "score": score,
                "dimensions": dimensions,
            }
        )

    economies.sort(key=lambda item: (-item["score"], item["economy"]))
    for index, economy in enumerate(economies, start=1):
        economy["rank"] = index

    by_economy = {economy["economy"]: economy for economy in economies}
    dimension_meta = [
        {
            "dimension": dimension,
            "shortLabel": DIMENSION_SHORT_LABELS.get(dimension, dimension),
            "maxScore": round(max_score, 4),
        }
        for dimension, max_score in weights.items()
    ]

    OUT_TS.write_text(
        "// Auto-generated by build_low_carbon_screener_data.py\n"
        "// Do not edit manually.\n\n"
        "export type LowCarbonScreenerDimension = { dimension: string; shortLabel: string; score: number; maxScore: number; normalized: number };\n\n"
        "export type LowCarbonScreenerEconomy = { economy: string; score: number; rank: number; dimensions: LowCarbonScreenerDimension[] };\n\n"
        f"export const LOW_CARBON_SCREENER_DIMENSIONS = {json.dumps(dimension_meta, ensure_ascii=False, indent=2)} as const;\n\n"
        f"export const LOW_CARBON_SCREENER_RANKING: LowCarbonScreenerEconomy[] = {json.dumps(economies, ensure_ascii=False, indent=2)};\n\n"
        f"export const LOW_CARBON_SCREENER_BY_ECONOMY: Record<string, LowCarbonScreenerEconomy> = {json.dumps(by_economy, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT_TS}")


if __name__ == "__main__":
    main()
