// Auto-generated by build_low_carbon_screener_data.py
// Do not edit manually.

export type LowCarbonScreenerDimension = { dimension: string; shortLabel: string; score: number; maxScore: number; normalized: number };

export type LowCarbonScreenerEconomy = { economy: string; score: number; rank: number; dimensions: LowCarbonScreenerDimension[]; profileLabel: string; profileColor: string; profileTone: string; strongAxes: string[] };

export const LOW_CARBON_SCREENER_DIMENSIONS = [
  {
    "dimension": "Need",
    "shortLabel": "Need Axis",
    "maxScore": 1
  },
  {
    "dimension": "Readiness",
    "shortLabel": "Readiness Axis",
    "maxScore": 1
  },
  {
    "dimension": "Financeability",
    "shortLabel": "Financeability Axis",
    "maxScore": 1
  }
] as const;

export const LOW_CARBON_SCREENER_RANKING: LowCarbonScreenerEconomy[] = [
  {
    "economy": "Niue",
    "score": 0.8335,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.9784,
        "maxScore": 1,
        "normalized": 97.84
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8902,
        "maxScore": 1,
        "normalized": 89.02
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6318,
        "maxScore": 1,
        "normalized": 63.18
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 1
  },
  {
    "economy": "Papua New Guinea",
    "score": 0.8137,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7676,
        "maxScore": 1,
        "normalized": 76.76
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9463,
        "maxScore": 1,
        "normalized": 94.63
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7273,
        "maxScore": 1,
        "normalized": 72.73
      }
    ],
    "profileLabel": "Strong pull across all three axes",
    "profileColor": "#E64B2A",
    "profileTone": "red",
    "strongAxes": [
      "Need",
      "Readiness",
      "Financeability"
    ],
    "rank": 2
  },
  {
    "economy": "Vanuatu",
    "score": 0.809,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6703,
        "maxScore": 1,
        "normalized": 67.03
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9293,
        "maxScore": 1,
        "normalized": 92.93
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.8273,
        "maxScore": 1,
        "normalized": 82.73
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 3
  },
  {
    "economy": "Nauru",
    "score": 0.8079,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.9108,
        "maxScore": 1,
        "normalized": 91.08
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8902,
        "maxScore": 1,
        "normalized": 89.02
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6227,
        "maxScore": 1,
        "normalized": 62.27
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 4
  },
  {
    "economy": "Micronesia (Federated States of)",
    "score": 0.7937,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7486,
        "maxScore": 1,
        "normalized": 74.86
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9098,
        "maxScore": 1,
        "normalized": 90.98
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7227,
        "maxScore": 1,
        "normalized": 72.27
      }
    ],
    "profileLabel": "Strong pull across all three axes",
    "profileColor": "#E64B2A",
    "profileTone": "red",
    "strongAxes": [
      "Need",
      "Readiness",
      "Financeability"
    ],
    "rank": 5
  },
  {
    "economy": "Turkmenistan",
    "score": 0.7916,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7622,
        "maxScore": 1,
        "normalized": 76.22
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8854,
        "maxScore": 1,
        "normalized": 88.54
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7273,
        "maxScore": 1,
        "normalized": 72.73
      }
    ],
    "profileLabel": "Strong pull across all three axes",
    "profileColor": "#E64B2A",
    "profileTone": "red",
    "strongAxes": [
      "Need",
      "Readiness",
      "Financeability"
    ],
    "rank": 6
  },
  {
    "economy": "Palau",
    "score": 0.7892,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.8243,
        "maxScore": 1,
        "normalized": 82.43
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9024,
        "maxScore": 1,
        "normalized": 90.24
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6409,
        "maxScore": 1,
        "normalized": 64.09
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 7
  },
  {
    "economy": "Cook Islands",
    "score": 0.7875,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.9243,
        "maxScore": 1,
        "normalized": 92.43
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.861,
        "maxScore": 1,
        "normalized": 86.1
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5773,
        "maxScore": 1,
        "normalized": 57.73
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 8
  },
  {
    "economy": "Pakistan",
    "score": 0.785,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7,
        "maxScore": 1,
        "normalized": 70.0
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9415,
        "maxScore": 1,
        "normalized": 94.15
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7136,
        "maxScore": 1,
        "normalized": 71.36
      }
    ],
    "profileLabel": "Strong pull across all three axes",
    "profileColor": "#E64B2A",
    "profileTone": "red",
    "strongAxes": [
      "Need",
      "Readiness",
      "Financeability"
    ],
    "rank": 9
  },
  {
    "economy": "Kiribati",
    "score": 0.7719,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6541,
        "maxScore": 1,
        "normalized": 65.41
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9024,
        "maxScore": 1,
        "normalized": 90.24
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7591,
        "maxScore": 1,
        "normalized": 75.91
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 10
  },
  {
    "economy": "Timor-Leste",
    "score": 0.7682,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7189,
        "maxScore": 1,
        "normalized": 71.89
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.922,
        "maxScore": 1,
        "normalized": 92.2
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6636,
        "maxScore": 1,
        "normalized": 66.36
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 11
  },
  {
    "economy": "Marshall Islands",
    "score": 0.7596,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6189,
        "maxScore": 1,
        "normalized": 61.89
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9463,
        "maxScore": 1,
        "normalized": 94.63
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7136,
        "maxScore": 1,
        "normalized": 71.36
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 12
  },
  {
    "economy": "Tuvalu",
    "score": 0.7558,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.8892,
        "maxScore": 1,
        "normalized": 88.92
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9146,
        "maxScore": 1,
        "normalized": 91.46
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.4636,
        "maxScore": 1,
        "normalized": 46.36
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 13
  },
  {
    "economy": "Afghanistan",
    "score": 0.7548,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7108,
        "maxScore": 1,
        "normalized": 71.08
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8171,
        "maxScore": 1,
        "normalized": 81.71
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7364,
        "maxScore": 1,
        "normalized": 73.64
      }
    ],
    "profileLabel": "Strong pull across all three axes",
    "profileColor": "#E64B2A",
    "profileTone": "red",
    "strongAxes": [
      "Need",
      "Readiness",
      "Financeability"
    ],
    "rank": 14
  },
  {
    "economy": "Kyrgyz Republic",
    "score": 0.7471,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.527,
        "maxScore": 1,
        "normalized": 52.7
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9098,
        "maxScore": 1,
        "normalized": 90.98
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.8045,
        "maxScore": 1,
        "normalized": 80.45
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 15
  },
  {
    "economy": "Myanmar",
    "score": 0.7432,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5811,
        "maxScore": 1,
        "normalized": 58.11
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9122,
        "maxScore": 1,
        "normalized": 91.22
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7364,
        "maxScore": 1,
        "normalized": 73.64
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 16
  },
  {
    "economy": "Mongolia",
    "score": 0.7385,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.627,
        "maxScore": 1,
        "normalized": 62.7
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9659,
        "maxScore": 1,
        "normalized": 96.59
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6227,
        "maxScore": 1,
        "normalized": 62.27
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 17
  },
  {
    "economy": "Nepal",
    "score": 0.7328,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4703,
        "maxScore": 1,
        "normalized": 47.03
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9463,
        "maxScore": 1,
        "normalized": 94.63
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7818,
        "maxScore": 1,
        "normalized": 78.18
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 18
  },
  {
    "economy": "Solomon Islands",
    "score": 0.7327,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6054,
        "maxScore": 1,
        "normalized": 60.54
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9244,
        "maxScore": 1,
        "normalized": 92.44
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6682,
        "maxScore": 1,
        "normalized": 66.82
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 19
  },
  {
    "economy": "Tajikistan",
    "score": 0.7154,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6081,
        "maxScore": 1,
        "normalized": 60.81
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8927,
        "maxScore": 1,
        "normalized": 89.27
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6455,
        "maxScore": 1,
        "normalized": 64.55
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 20
  },
  {
    "economy": "Philippines",
    "score": 0.7138,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.573,
        "maxScore": 1,
        "normalized": 57.3
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9366,
        "maxScore": 1,
        "normalized": 93.66
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6318,
        "maxScore": 1,
        "normalized": 63.18
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 21
  },
  {
    "economy": "Lao People's Democratic Republic",
    "score": 0.7112,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4297,
        "maxScore": 1,
        "normalized": 42.97
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9585,
        "maxScore": 1,
        "normalized": 95.85
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7455,
        "maxScore": 1,
        "normalized": 74.55
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 22
  },
  {
    "economy": "Tonga",
    "score": 0.7,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6649,
        "maxScore": 1,
        "normalized": 66.49
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8805,
        "maxScore": 1,
        "normalized": 88.05
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5545,
        "maxScore": 1,
        "normalized": 55.45
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 23
  },
  {
    "economy": "Maldives",
    "score": 0.698,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7108,
        "maxScore": 1,
        "normalized": 71.08
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8195,
        "maxScore": 1,
        "normalized": 81.95
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5636,
        "maxScore": 1,
        "normalized": 56.36
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 24
  },
  {
    "economy": "Samoa",
    "score": 0.6972,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6108,
        "maxScore": 1,
        "normalized": 61.08
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8854,
        "maxScore": 1,
        "normalized": 88.54
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5955,
        "maxScore": 1,
        "normalized": 59.55
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 25
  },
  {
    "economy": "Sri Lanka",
    "score": 0.6881,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4216,
        "maxScore": 1,
        "normalized": 42.16
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.861,
        "maxScore": 1,
        "normalized": 86.1
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7818,
        "maxScore": 1,
        "normalized": 78.18
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 26
  },
  {
    "economy": "Fiji",
    "score": 0.6837,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4919,
        "maxScore": 1,
        "normalized": 49.19
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8683,
        "maxScore": 1,
        "normalized": 86.83
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6909,
        "maxScore": 1,
        "normalized": 69.09
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 27
  },
  {
    "economy": "Azerbaijan",
    "score": 0.6782,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5054,
        "maxScore": 1,
        "normalized": 50.54
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.861,
        "maxScore": 1,
        "normalized": 86.1
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6682,
        "maxScore": 1,
        "normalized": 66.82
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 28
  },
  {
    "economy": "Bhutan",
    "score": 0.6705,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4459,
        "maxScore": 1,
        "normalized": 44.59
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.861,
        "maxScore": 1,
        "normalized": 86.1
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7045,
        "maxScore": 1,
        "normalized": 70.45
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 29
  },
  {
    "economy": "Türkiye",
    "score": 0.6661,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5946,
        "maxScore": 1,
        "normalized": 59.46
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.6902,
        "maxScore": 1,
        "normalized": 69.02
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7136,
        "maxScore": 1,
        "normalized": 71.36
      }
    ],
    "profileLabel": "Focused pull on financeability",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Financeability"
    ],
    "rank": 30
  },
  {
    "economy": "Uzbekistan",
    "score": 0.6604,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4,
        "maxScore": 1,
        "normalized": 40.0
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8902,
        "maxScore": 1,
        "normalized": 89.02
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6909,
        "maxScore": 1,
        "normalized": 69.09
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 31
  },
  {
    "economy": "Viet Nam",
    "score": 0.6585,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5838,
        "maxScore": 1,
        "normalized": 58.38
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.7463,
        "maxScore": 1,
        "normalized": 74.63
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6455,
        "maxScore": 1,
        "normalized": 64.55
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 32
  },
  {
    "economy": "Bangladesh",
    "score": 0.6512,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.473,
        "maxScore": 1,
        "normalized": 47.3
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8488,
        "maxScore": 1,
        "normalized": 84.88
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6318,
        "maxScore": 1,
        "normalized": 63.18
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 33
  },
  {
    "economy": "India",
    "score": 0.6341,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5162,
        "maxScore": 1,
        "normalized": 51.62
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.6951,
        "maxScore": 1,
        "normalized": 69.51
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6909,
        "maxScore": 1,
        "normalized": 69.09
      }
    ],
    "profileLabel": "Overall low to moderate focus",
    "profileColor": "#4E9BC3",
    "profileTone": "blue",
    "strongAxes": [],
    "rank": 34
  },
  {
    "economy": "Georgia",
    "score": 0.6312,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.3865,
        "maxScore": 1,
        "normalized": 38.65
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.839,
        "maxScore": 1,
        "normalized": 83.9
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6682,
        "maxScore": 1,
        "normalized": 66.82
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 35
  },
  {
    "economy": "Cambodia",
    "score": 0.6293,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4838,
        "maxScore": 1,
        "normalized": 48.38
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.7951,
        "maxScore": 1,
        "normalized": 79.51
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6091,
        "maxScore": 1,
        "normalized": 60.91
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 36
  },
  {
    "economy": "Malaysia",
    "score": 0.6046,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5216,
        "maxScore": 1,
        "normalized": 52.16
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.5878,
        "maxScore": 1,
        "normalized": 58.78
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7045,
        "maxScore": 1,
        "normalized": 70.45
      }
    ],
    "profileLabel": "Focused pull on financeability",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Financeability"
    ],
    "rank": 37
  },
  {
    "economy": "Indonesia",
    "score": 0.6028,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4378,
        "maxScore": 1,
        "normalized": 43.78
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.6707,
        "maxScore": 1,
        "normalized": 67.07
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7,
        "maxScore": 1,
        "normalized": 70.0
      }
    ],
    "profileLabel": "Focused pull on financeability",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Financeability"
    ],
    "rank": 38
  },
  {
    "economy": "People's Republic of China",
    "score": 0.597,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5649,
        "maxScore": 1,
        "normalized": 56.49
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.6488,
        "maxScore": 1,
        "normalized": 64.88
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5773,
        "maxScore": 1,
        "normalized": 57.73
      }
    ],
    "profileLabel": "Overall low to moderate focus",
    "profileColor": "#4E9BC3",
    "profileTone": "blue",
    "strongAxes": [],
    "rank": 39
  },
  {
    "economy": "Kazakhstan",
    "score": 0.5866,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4135,
        "maxScore": 1,
        "normalized": 41.35
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8146,
        "maxScore": 1,
        "normalized": 81.46
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5318,
        "maxScore": 1,
        "normalized": 53.18
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 40
  },
  {
    "economy": "Armenia",
    "score": 0.5846,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.3676,
        "maxScore": 1,
        "normalized": 36.76
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.7634,
        "maxScore": 1,
        "normalized": 76.34
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6227,
        "maxScore": 1,
        "normalized": 62.27
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 41
  },
  {
    "economy": "Thailand",
    "score": 0.5542,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4297,
        "maxScore": 1,
        "normalized": 42.97
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.7146,
        "maxScore": 1,
        "normalized": 71.46
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5182,
        "maxScore": 1,
        "normalized": 51.82
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 42
  }
];

export const LOW_CARBON_SCREENER_BY_ECONOMY: Record<string, LowCarbonScreenerEconomy> = {
  "Niue": {
    "economy": "Niue",
    "score": 0.8335,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.9784,
        "maxScore": 1,
        "normalized": 97.84
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8902,
        "maxScore": 1,
        "normalized": 89.02
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6318,
        "maxScore": 1,
        "normalized": 63.18
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 1
  },
  "Papua New Guinea": {
    "economy": "Papua New Guinea",
    "score": 0.8137,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7676,
        "maxScore": 1,
        "normalized": 76.76
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9463,
        "maxScore": 1,
        "normalized": 94.63
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7273,
        "maxScore": 1,
        "normalized": 72.73
      }
    ],
    "profileLabel": "Strong pull across all three axes",
    "profileColor": "#E64B2A",
    "profileTone": "red",
    "strongAxes": [
      "Need",
      "Readiness",
      "Financeability"
    ],
    "rank": 2
  },
  "Vanuatu": {
    "economy": "Vanuatu",
    "score": 0.809,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6703,
        "maxScore": 1,
        "normalized": 67.03
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9293,
        "maxScore": 1,
        "normalized": 92.93
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.8273,
        "maxScore": 1,
        "normalized": 82.73
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 3
  },
  "Nauru": {
    "economy": "Nauru",
    "score": 0.8079,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.9108,
        "maxScore": 1,
        "normalized": 91.08
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8902,
        "maxScore": 1,
        "normalized": 89.02
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6227,
        "maxScore": 1,
        "normalized": 62.27
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 4
  },
  "Micronesia (Federated States of)": {
    "economy": "Micronesia (Federated States of)",
    "score": 0.7937,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7486,
        "maxScore": 1,
        "normalized": 74.86
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9098,
        "maxScore": 1,
        "normalized": 90.98
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7227,
        "maxScore": 1,
        "normalized": 72.27
      }
    ],
    "profileLabel": "Strong pull across all three axes",
    "profileColor": "#E64B2A",
    "profileTone": "red",
    "strongAxes": [
      "Need",
      "Readiness",
      "Financeability"
    ],
    "rank": 5
  },
  "Turkmenistan": {
    "economy": "Turkmenistan",
    "score": 0.7916,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7622,
        "maxScore": 1,
        "normalized": 76.22
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8854,
        "maxScore": 1,
        "normalized": 88.54
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7273,
        "maxScore": 1,
        "normalized": 72.73
      }
    ],
    "profileLabel": "Strong pull across all three axes",
    "profileColor": "#E64B2A",
    "profileTone": "red",
    "strongAxes": [
      "Need",
      "Readiness",
      "Financeability"
    ],
    "rank": 6
  },
  "Palau": {
    "economy": "Palau",
    "score": 0.7892,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.8243,
        "maxScore": 1,
        "normalized": 82.43
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9024,
        "maxScore": 1,
        "normalized": 90.24
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6409,
        "maxScore": 1,
        "normalized": 64.09
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 7
  },
  "Cook Islands": {
    "economy": "Cook Islands",
    "score": 0.7875,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.9243,
        "maxScore": 1,
        "normalized": 92.43
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.861,
        "maxScore": 1,
        "normalized": 86.1
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5773,
        "maxScore": 1,
        "normalized": 57.73
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 8
  },
  "Pakistan": {
    "economy": "Pakistan",
    "score": 0.785,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7,
        "maxScore": 1,
        "normalized": 70.0
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9415,
        "maxScore": 1,
        "normalized": 94.15
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7136,
        "maxScore": 1,
        "normalized": 71.36
      }
    ],
    "profileLabel": "Strong pull across all three axes",
    "profileColor": "#E64B2A",
    "profileTone": "red",
    "strongAxes": [
      "Need",
      "Readiness",
      "Financeability"
    ],
    "rank": 9
  },
  "Kiribati": {
    "economy": "Kiribati",
    "score": 0.7719,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6541,
        "maxScore": 1,
        "normalized": 65.41
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9024,
        "maxScore": 1,
        "normalized": 90.24
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7591,
        "maxScore": 1,
        "normalized": 75.91
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 10
  },
  "Timor-Leste": {
    "economy": "Timor-Leste",
    "score": 0.7682,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7189,
        "maxScore": 1,
        "normalized": 71.89
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.922,
        "maxScore": 1,
        "normalized": 92.2
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6636,
        "maxScore": 1,
        "normalized": 66.36
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 11
  },
  "Marshall Islands": {
    "economy": "Marshall Islands",
    "score": 0.7596,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6189,
        "maxScore": 1,
        "normalized": 61.89
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9463,
        "maxScore": 1,
        "normalized": 94.63
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7136,
        "maxScore": 1,
        "normalized": 71.36
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 12
  },
  "Tuvalu": {
    "economy": "Tuvalu",
    "score": 0.7558,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.8892,
        "maxScore": 1,
        "normalized": 88.92
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9146,
        "maxScore": 1,
        "normalized": 91.46
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.4636,
        "maxScore": 1,
        "normalized": 46.36
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 13
  },
  "Afghanistan": {
    "economy": "Afghanistan",
    "score": 0.7548,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7108,
        "maxScore": 1,
        "normalized": 71.08
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8171,
        "maxScore": 1,
        "normalized": 81.71
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7364,
        "maxScore": 1,
        "normalized": 73.64
      }
    ],
    "profileLabel": "Strong pull across all three axes",
    "profileColor": "#E64B2A",
    "profileTone": "red",
    "strongAxes": [
      "Need",
      "Readiness",
      "Financeability"
    ],
    "rank": 14
  },
  "Kyrgyz Republic": {
    "economy": "Kyrgyz Republic",
    "score": 0.7471,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.527,
        "maxScore": 1,
        "normalized": 52.7
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9098,
        "maxScore": 1,
        "normalized": 90.98
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.8045,
        "maxScore": 1,
        "normalized": 80.45
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 15
  },
  "Myanmar": {
    "economy": "Myanmar",
    "score": 0.7432,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5811,
        "maxScore": 1,
        "normalized": 58.11
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9122,
        "maxScore": 1,
        "normalized": 91.22
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7364,
        "maxScore": 1,
        "normalized": 73.64
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 16
  },
  "Mongolia": {
    "economy": "Mongolia",
    "score": 0.7385,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.627,
        "maxScore": 1,
        "normalized": 62.7
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9659,
        "maxScore": 1,
        "normalized": 96.59
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6227,
        "maxScore": 1,
        "normalized": 62.27
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 17
  },
  "Nepal": {
    "economy": "Nepal",
    "score": 0.7328,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4703,
        "maxScore": 1,
        "normalized": 47.03
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9463,
        "maxScore": 1,
        "normalized": 94.63
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7818,
        "maxScore": 1,
        "normalized": 78.18
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 18
  },
  "Solomon Islands": {
    "economy": "Solomon Islands",
    "score": 0.7327,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6054,
        "maxScore": 1,
        "normalized": 60.54
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9244,
        "maxScore": 1,
        "normalized": 92.44
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6682,
        "maxScore": 1,
        "normalized": 66.82
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 19
  },
  "Tajikistan": {
    "economy": "Tajikistan",
    "score": 0.7154,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6081,
        "maxScore": 1,
        "normalized": 60.81
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8927,
        "maxScore": 1,
        "normalized": 89.27
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6455,
        "maxScore": 1,
        "normalized": 64.55
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 20
  },
  "Philippines": {
    "economy": "Philippines",
    "score": 0.7138,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.573,
        "maxScore": 1,
        "normalized": 57.3
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9366,
        "maxScore": 1,
        "normalized": 93.66
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6318,
        "maxScore": 1,
        "normalized": 63.18
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 21
  },
  "Lao People's Democratic Republic": {
    "economy": "Lao People's Democratic Republic",
    "score": 0.7112,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4297,
        "maxScore": 1,
        "normalized": 42.97
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.9585,
        "maxScore": 1,
        "normalized": 95.85
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7455,
        "maxScore": 1,
        "normalized": 74.55
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 22
  },
  "Tonga": {
    "economy": "Tonga",
    "score": 0.7,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6649,
        "maxScore": 1,
        "normalized": 66.49
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8805,
        "maxScore": 1,
        "normalized": 88.05
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5545,
        "maxScore": 1,
        "normalized": 55.45
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 23
  },
  "Maldives": {
    "economy": "Maldives",
    "score": 0.698,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.7108,
        "maxScore": 1,
        "normalized": 71.08
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8195,
        "maxScore": 1,
        "normalized": 81.95
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5636,
        "maxScore": 1,
        "normalized": 56.36
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Need",
      "Readiness"
    ],
    "rank": 24
  },
  "Samoa": {
    "economy": "Samoa",
    "score": 0.6972,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.6108,
        "maxScore": 1,
        "normalized": 61.08
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8854,
        "maxScore": 1,
        "normalized": 88.54
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5955,
        "maxScore": 1,
        "normalized": 59.55
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 25
  },
  "Sri Lanka": {
    "economy": "Sri Lanka",
    "score": 0.6881,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4216,
        "maxScore": 1,
        "normalized": 42.16
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.861,
        "maxScore": 1,
        "normalized": 86.1
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7818,
        "maxScore": 1,
        "normalized": 78.18
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 26
  },
  "Fiji": {
    "economy": "Fiji",
    "score": 0.6837,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4919,
        "maxScore": 1,
        "normalized": 49.19
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8683,
        "maxScore": 1,
        "normalized": 86.83
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6909,
        "maxScore": 1,
        "normalized": 69.09
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 27
  },
  "Azerbaijan": {
    "economy": "Azerbaijan",
    "score": 0.6782,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5054,
        "maxScore": 1,
        "normalized": 50.54
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.861,
        "maxScore": 1,
        "normalized": 86.1
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6682,
        "maxScore": 1,
        "normalized": 66.82
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 28
  },
  "Bhutan": {
    "economy": "Bhutan",
    "score": 0.6705,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4459,
        "maxScore": 1,
        "normalized": 44.59
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.861,
        "maxScore": 1,
        "normalized": 86.1
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7045,
        "maxScore": 1,
        "normalized": 70.45
      }
    ],
    "profileLabel": "Stronger pull across two axes",
    "profileColor": "#F5C400",
    "profileTone": "yellow",
    "strongAxes": [
      "Readiness",
      "Financeability"
    ],
    "rank": 29
  },
  "Türkiye": {
    "economy": "Türkiye",
    "score": 0.6661,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5946,
        "maxScore": 1,
        "normalized": 59.46
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.6902,
        "maxScore": 1,
        "normalized": 69.02
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7136,
        "maxScore": 1,
        "normalized": 71.36
      }
    ],
    "profileLabel": "Focused pull on financeability",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Financeability"
    ],
    "rank": 30
  },
  "Uzbekistan": {
    "economy": "Uzbekistan",
    "score": 0.6604,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4,
        "maxScore": 1,
        "normalized": 40.0
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8902,
        "maxScore": 1,
        "normalized": 89.02
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6909,
        "maxScore": 1,
        "normalized": 69.09
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 31
  },
  "Viet Nam": {
    "economy": "Viet Nam",
    "score": 0.6585,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5838,
        "maxScore": 1,
        "normalized": 58.38
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.7463,
        "maxScore": 1,
        "normalized": 74.63
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6455,
        "maxScore": 1,
        "normalized": 64.55
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 32
  },
  "Bangladesh": {
    "economy": "Bangladesh",
    "score": 0.6512,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.473,
        "maxScore": 1,
        "normalized": 47.3
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8488,
        "maxScore": 1,
        "normalized": 84.88
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6318,
        "maxScore": 1,
        "normalized": 63.18
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 33
  },
  "India": {
    "economy": "India",
    "score": 0.6341,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5162,
        "maxScore": 1,
        "normalized": 51.62
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.6951,
        "maxScore": 1,
        "normalized": 69.51
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6909,
        "maxScore": 1,
        "normalized": 69.09
      }
    ],
    "profileLabel": "Overall low to moderate focus",
    "profileColor": "#4E9BC3",
    "profileTone": "blue",
    "strongAxes": [],
    "rank": 34
  },
  "Georgia": {
    "economy": "Georgia",
    "score": 0.6312,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.3865,
        "maxScore": 1,
        "normalized": 38.65
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.839,
        "maxScore": 1,
        "normalized": 83.9
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6682,
        "maxScore": 1,
        "normalized": 66.82
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 35
  },
  "Cambodia": {
    "economy": "Cambodia",
    "score": 0.6293,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4838,
        "maxScore": 1,
        "normalized": 48.38
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.7951,
        "maxScore": 1,
        "normalized": 79.51
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6091,
        "maxScore": 1,
        "normalized": 60.91
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 36
  },
  "Malaysia": {
    "economy": "Malaysia",
    "score": 0.6046,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5216,
        "maxScore": 1,
        "normalized": 52.16
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.5878,
        "maxScore": 1,
        "normalized": 58.78
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7045,
        "maxScore": 1,
        "normalized": 70.45
      }
    ],
    "profileLabel": "Focused pull on financeability",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Financeability"
    ],
    "rank": 37
  },
  "Indonesia": {
    "economy": "Indonesia",
    "score": 0.6028,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4378,
        "maxScore": 1,
        "normalized": 43.78
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.6707,
        "maxScore": 1,
        "normalized": 67.07
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.7,
        "maxScore": 1,
        "normalized": 70.0
      }
    ],
    "profileLabel": "Focused pull on financeability",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Financeability"
    ],
    "rank": 38
  },
  "People's Republic of China": {
    "economy": "People's Republic of China",
    "score": 0.597,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.5649,
        "maxScore": 1,
        "normalized": 56.49
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.6488,
        "maxScore": 1,
        "normalized": 64.88
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5773,
        "maxScore": 1,
        "normalized": 57.73
      }
    ],
    "profileLabel": "Overall low to moderate focus",
    "profileColor": "#4E9BC3",
    "profileTone": "blue",
    "strongAxes": [],
    "rank": 39
  },
  "Kazakhstan": {
    "economy": "Kazakhstan",
    "score": 0.5866,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4135,
        "maxScore": 1,
        "normalized": 41.35
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.8146,
        "maxScore": 1,
        "normalized": 81.46
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5318,
        "maxScore": 1,
        "normalized": 53.18
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 40
  },
  "Armenia": {
    "economy": "Armenia",
    "score": 0.5846,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.3676,
        "maxScore": 1,
        "normalized": 36.76
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.7634,
        "maxScore": 1,
        "normalized": 76.34
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.6227,
        "maxScore": 1,
        "normalized": 62.27
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 41
  },
  "Thailand": {
    "economy": "Thailand",
    "score": 0.5542,
    "dimensions": [
      {
        "dimension": "Need",
        "shortLabel": "Need Axis",
        "score": 0.4297,
        "maxScore": 1,
        "normalized": 42.97
      },
      {
        "dimension": "Readiness",
        "shortLabel": "Readiness Axis",
        "score": 0.7146,
        "maxScore": 1,
        "normalized": 71.46
      },
      {
        "dimension": "Financeability",
        "shortLabel": "Financeability Axis",
        "score": 0.5182,
        "maxScore": 1,
        "normalized": 51.82
      }
    ],
    "profileLabel": "Focused pull on readiness",
    "profileColor": "#9EBB1B",
    "profileTone": "green",
    "strongAxes": [
      "Readiness"
    ],
    "rank": 42
  }
};
