// Auto-generated by build_theme_dashboard_data.py
// Do not edit manually.

export type ThemeId = "e_mobility" | "active_transport" | "urban_transport";

export type ThemeRankingRow = { label: string; commitment: number; disbursement: number; commitment_defl: number; disbursement_defl: number; count: number };

export type ThemeRecord = { rowNumber: string; year: number | null; donor: string; recipient: string; mode: string; flow: string; commitment_defl: number; disbursement_defl: number; title: string; description: string; tags: string[]; needsReview: boolean };

export type ThemeSankeyNode = { id: string; name: string; role: 'donor' | 'subtag' | 'recipient'; totalValue: number; color?: string };

export type ThemeSankeyLink = { source: number; target: number; sourceName: string; targetName: string; value: number; flowType?: string; color?: string };

export type ThemeSankeyData = { nodes: ThemeSankeyNode[]; links: ThemeSankeyLink[] };

export type ThemeRecordsByTheme = Record<ThemeId, ThemeRecord[]>;

export const THEME_RECORDS_URL = './data/theme-records.json';

export const THEME_SUMMARIES = [
  {
    "id": "e_mobility",
    "label": "E-Mobility",
    "shortLabel": "E-Mobility",
    "description": "Projects explicitly supporting electric mobility, electric vehicles, charging or battery infrastructure, grid integration, electric freight and logistics, EV finance, pilots, skills, data, or inclusion.",
    "color": "#0891B2",
    "recordCount": 313,
    "commitment": 4400.673,
    "disbursement": 681.9782,
    "commitment_defl": 4395.7442,
    "disbursement_defl": 710.3791,
    "donorCount": 23,
    "recipientCount": 23,
    "yearMin": 1996,
    "yearMax": 2024,
    "topMode": "Other"
  },
  {
    "id": "active_transport",
    "label": "Active Transport",
    "shortLabel": "Active Transport",
    "description": "Projects supporting walking, cycling, non-motorized transport, pedestrian infrastructure, cycling facilities, safe active mobility, complete streets, and first/last-mile active access.",
    "color": "#65A30D",
    "recordCount": 408,
    "commitment": 3681.1721,
    "disbursement": 998.2295,
    "commitment_defl": 3989.132,
    "disbursement_defl": 1128.3449,
    "donorCount": 18,
    "recipientCount": 21,
    "yearMin": 1989,
    "yearMax": 2024,
    "topMode": "Other"
  },
  {
    "id": "urban_transport",
    "label": "Urban Transport",
    "shortLabel": "Urban Transport",
    "description": "Projects focused on mobility within cities, towns, metropolitan areas, or other urban settlements, including public transport, urban roads and streets, traffic management, terminals, multimodal integration, TOD, shared mobility, and urban logistics.",
    "color": "#4F46E5",
    "recordCount": 8768,
    "commitment": 102124.5315,
    "disbursement": 59642.7182,
    "commitment_defl": 97076.0143,
    "disbursement_defl": 56114.5031,
    "donorCount": 41,
    "recipientCount": 41,
    "yearMin": 1977,
    "yearMax": 2024,
    "topMode": "Rail"
  }
] as const;

